---
language: rust
cache: cargo
rust: beta

os:
  - windows
  - linux
  - osx

branches:
  only:
    - master

notifications:
  email: false
  slack:
    secure: slRWxWp06BxwQUCZKb3uXNhEgdJxnBrtYFfZ+ng/S/mxCCGMH1tt/amaxVEqbOIypedx9FI2TDRDGmbPAQJBFtP75pPM3bYn0mqU/vOGeGLzxqTeitw7gp/1Ybr7e1O//sIav5i4z8O1kGeQcEzfbkNS43jcLk0FvtasBWwGGs2n9pX3sNatJrGzCVkKJoJ1DFPi6ax7Ph3Rhi4ebFHS8B5lBAykBUG6Ngr3WPeRx9gDZXxs4IY6Gntu2e+4Kdrft6AD5VdUSp1XlFS/9S+suc/426oQQg8IEnk/xJMLl4BLB+NMlvBYj527mVczWAN3PooGtDU5jt/NUkxhpUu/Gxe5FvZgf2eS8l8gAEwz4nFU/BafdqcScRdqYA9ZP/GhZCOPVAd5ZFvS0tm38L0Ne8OfR+lyM5T0kSjPmLoeFnTzC/I4Am3EXjmHwt+XMcCxMcZ62Cy0Oeh1H1Q89MwGGm/KDfmBhJ/lVcXnvWB2WCyQ5+9ew385N9I/oyg27wfPEVsHiDii7YNusA3HW9AqeKOp5KddWn2BjcRkzxXgt81FgMywGnLTVdVQx/8Wu2T1xxVSgZq1iqskn6mD27CyoPFXYbYt/2sCuseIi96F1iPL2XX3ryDrle/jm/5GEI4P3bLQ6mV4SMSoqdglYiTZYpDrd85AwBegDR+7oksy8RI=
  on_success: change
  on_failure: always
  notify: true
