---
language: rust
cache: cargo
rust: beta

os:
  - windows
  - linux
  - osx

branches:
  only:
    - master

notifications:
  email: false
  slack: esanum:XFAkvhriKLtaV89LA5CUnSEN
  on_success: change
  on_failure: always
  notify: true
